# ===============================
# Database Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/stockpilot
spring.datasource.username=postgres
spring.datasource.password=StockPilot_DB_2026!
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Flyway Configuration
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# ===============================
# Server
# ===============================

server.port=8080